#!/usr/bin/env python3
"""ffmpeg -> 1-bit XBM frames -> video_frames.h for giga-r1/oled_video_test.

usage: pack_xbm.py <video> <out.h> [fps] [w] [h] [white] [seconds]
Center-crops to the panel's aspect (the panel is portrait, the source is 16:9),
error-diffusion dithers, packs LSB-first like XBM wants.
"""
import re, subprocess, sys

src, out = sys.argv[1], sys.argv[2]
fps = float(sys.argv[3]) if len(sys.argv) > 3 else 8
W = int(sys.argv[4]) if len(sys.argv) > 4 else 64
H = int(sys.argv[5]) if len(sys.argv) > 5 else 128
white = float(sys.argv[6]) if len(sys.argv) > 6 else 0.15
secs = sys.argv[7] if len(sys.argv) > 7 else None  # clip length — flash caps this, ~1KB/frame
stride = (W + 7) // 8

# IMPORTANT NOTE: `white` is the input level that gets stretched to full white, so it is the
# one knob to turn per clip: lower it for a dark source, raise it for a bright one. Do NOT
# reach for eq=contrast here — eq pivots around mid-gray, so on a dark clip (GRIEF averages
# 6/255) it pushes everything *below* the 1-bit threshold and packs 1.5MB of pure black.
# The curve lifts the black end instead, which is what a near-black source actually needs.
# memes are routinely a portrait video pillarboxed inside a 16:9 file; without this the
# panel spends most of its 64 columns on the black bars. cropdetect off a mid-clip sample.
probe = subprocess.run(
    ["ffmpeg", "-hide_banner", "-ss", "5", "-i", src, "-frames:v", "40",
     "-vf", "cropdetect=limit=24:round=2", "-f", "null", "-"],
    stderr=subprocess.PIPE, text=True).stderr
bars = re.findall(r"crop=(\d+:\d+:\d+:\d+)", probe)
bars = f"crop={bars[-1]}," if bars else ""

vf = (f"fps={fps},{bars}scale={W}:{H}:force_original_aspect_ratio=increase,crop={W}:{H},"
      f"format=gray,curves=all='0/0 {white*0.4:.3f}/0.5 {white:.3f}/1 1/1',format=monob")
raw = subprocess.run(
    ["ffmpeg", "-v", "error", "-i", src, "-sws_dither", "ed"]
    + (["-t", secs] if secs else [])
    + ["-vf", vf, "-f", "rawvideo", "-pix_fmt", "monob", "-"],
    stdout=subprocess.PIPE, check=True).stdout

REV = bytes(int(f"{b:08b}"[::-1], 2) for b in range(256))  # monob is MSB-first, XBM is LSB-first
size = stride * H
n = len(raw) // size
assert n and len(raw) % size == 0, f"{len(raw)} bytes is not a whole number of {size}B frames"

# a blank panel looks exactly like broken wiring, so refuse to emit a clip that can't be seen
ink = 100 * sum(bin(b).count("1") for b in raw) / (len(raw) * 8)
assert ink > 1.0, f"only {ink:.2f}% of pixels lit — source too dark, lower `white` (now {white})"

with open(out, "w") as f:
    f.write("// generated by pack_xbm.py — bench test only, not part of the real build\n"
            "#pragma once\n#include <Arduino.h>\n\n")
    for i in range(n):
        px = raw[i * size:(i + 1) * size].translate(REV)
        f.write(f"const uint8_t frame_{i:03d}[] PROGMEM = {{"
                + ",".join(f"0x{b:02X}" for b in px) + "};\n")
    f.write("\nconst uint8_t* const video_frames[] PROGMEM = {"
            + ",".join(f"frame_{i:03d}" for i in range(n)) + "};\n")
    f.write(f"const uint16_t VIDEO_FRAME_COUNT = {n};\n"
            f"const uint16_t VIDEO_FRAME_W = {W};\n"
            f"const uint16_t VIDEO_FRAME_H = {H};\n")

print(f"{n} frames, {n * size / 1024:.0f} KB flash, {ink:.1f}% pixels lit")
