name: Arduino Compile

on:
  push:
    paths:
      - "giga-r1/**"
  pull_request:
    paths:
      - "giga-r1/**"

jobs:
  compile-giga-r1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: arduino:mbed_giga:giga
          sketch-paths: giga-r1/main
          libraries: |
            - name: ArduinoBLE
            - name: DHT11
